use lccsjce;
select * from user_details;
select * from student_details;
select * from guardian_details;
select * from deg_details;
select * from bank_details;
select * from basicaddress_details where stu_admissionnumber='777' and ad_degree='ug';
select * from entrance_test;
select * from local_address;
delete from student_details where stu_id=1;
alter table student_details AUTO_INCREMENT=1;
alter table deg_details AUTO_INCREMENT=1;
alter table bank_details AUTO_INCREMENT=1;
alter table basicaddress_details AUTO_INCREMENT=1;
alter table entrance_test AUTO_INCREMENT=1;
alter table local_address AUTO_INCREMENT=1;
alter table guardian_details AUTO_INCREMENT=1;
delete from student_details where stu_id=11;
update student_details set stu_admissionnumber=2 where stu_id=10;
Select stu_id,stu_admissionnumber from student_details where stu_admissionnumber='1234';